# Generated by Django 3.1.3 on 2022-01-05 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freebo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replying',
            old_name='title',
            new_name='freewriting',
        ),
        migrations.AddField(
            model_name='freewriting',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freewriting',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replying',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='replying',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
